version: "3"
services:
    backend:
        build: ./backend
        ports:
            - "3000:3000"
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: postgres:11.5-alpine
        ports:
            - "5432:5432"
        volumes:
            - ./db:/var/lib/postgresql/data
        env_file:
            - .env
    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - "4000:4000"
        env_file:
            - .env
